import Link from "next/link"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body style={{ backgroundColor: 'red' }}>
                <Link href='./'>Home</Link>
                <Link href='./public'>Public</Link>
                <Link href='./order'>Order</Link>
                <Link href='./user'>User</Link>
                <Link href='./cart'>Cart</Link>
                <Link href='./shop'>Shop</Link>
                <Link href='./colocate'>Colocate</Link>
                <Link href='./error'>Error</Link>
                {children}</body>
        </html>
    )
}
