import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex gap-4 font-bold'>
          <Link href='./'>Home</Link>
          <Link href='./public'>Public</Link>
          <Link href='./order'>Order</Link>
          <Link href='./user'>User</Link>
          <Link href='./cart'>Cart</Link>
          <Link href='./shop'>Shop</Link>
          <Link href='./colocate'>ColocateErr</Link>
          <Link href='./error'>Error</Link>
          <Link href='./fetch'>Fetch</Link></div>
        {children}</body>
    </html>
  )
}
